<a href="https://colab.research.google.com/github/pavithrankb/web/blob/master/cnn_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from datetime import datetime
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.layers.convolutional import Conv1D, MaxPooling1D

In [2]:
df = pd.read_csv("cleaned_finalset.csv", header=0, index_col=0)
df.describe()

AT            BP          PM10         PM2.5            RH  \
count  59729.000000  59729.000000  59729.000000  59729.000000  59729.000000   
mean      26.761003    850.219439    339.027284    149.560628     53.271846   
std        7.675111    116.928588    193.867059    118.273865     18.710940   
min        0.000000    727.080000      1.000000      0.000000      0.230000   
25%       23.180000    739.939021    195.000000     66.000000     43.980000   
50%       26.841534    740.000000    332.500000    123.250000     52.050000   
75%       31.730000    973.320000    443.037470    192.375085     65.750000   
max      362.000000    999.900000   1000.000000    985.000000     99.700000   

                 WD            WS            CO           NH3            NO  \
count  59729.000000  59729.000000  59729.000000  59729.000000  59729.000000   
mean     190.511807      1.133667      2.217027     53.016956     90.944444   
std       70.626960      0.923021      1.368005     30.406303     88.094263   
min        4.080000      0.000000      0.000000      0.100000      0.100000   
25%      125.250000      0.340000      1.480000     33.200000     30.500000   
50%      199.727403      0.960000      2.095170     48.220000     86.490000   
75%      256.600000      1.570000      2.592207     67.320000    104.938665   
max      340.500000      8.980000     29.200000    575.240000    990.830000   

                NO2           NOx         Ozone           SO2  
count  59729.000000  59729.000000  59729.000000  59729.000000  
mean      85.832311    150.551397     31.823307     18.951550  
std       48.180128    110.569422     25.965558     16.274912  
min        0.100000      0.000000      0.100000      0.000000  
25%       54.170000     70.550000     15.620000      9.820000  
50%       80.650000    128.832838     26.637027     16.420000  
75%      109.599813    214.506152     34.225155     23.380207  
max      659.080000    993.030000    229.900000    940.500000

In [3]:
dataset_columns = df.columns.tolist()
dataset_columns

['From Date',
 'To Date',
 'AT',
 'BP',
 'PM10',
 'PM2.5',
 'RH',
 'WD',
 'WS',
 'CO',
 'NH3',
 'NO',
 'NO2',
 'NOx',
 'Ozone',
 'SO2']

In [4]:
df = df.drop(['From Date','To Date',
 'AT',
 'BP',
 'PM2.5',
 'RH',
 'WD',
 'WS',
 'CO',
 'NH3',
 'NO',
 'NO2',
 'NOx',
 'SO2',
 'Ozone'
 ],axis = 1)
df.head()

PM10
0  444.669402
1  444.669402
2  444.669402
3  444.669402
4  444.669402

In [5]:
df

PM10
0      444.669402
1      444.669402
2      444.669402
3      444.669402
4      444.669402
...           ...
59724  515.000000
59725  450.000000
59726  437.000000
59727  397.250000
59728  395.000000

[59729 rows x 1 columns]

In [6]:
def split_seq(sequence, steps):
  x,y = list(), list()
  for start in range(len(sequence)):
    end=start+steps
    if end>len(sequence)-1:
      break
    seqx,seqy = sequence[start : end], sequence[end]
    x.append(seqx)
    y.append(seqy)
  return np.array(x),np.array(y)


In [7]:
actual_seq=list(df['PM10'])

In [8]:
sample_seq=actual_seq

In [9]:
steps= 1000
x,y = split_seq(sample_seq , steps)
print("----------------")
print("raw")
print(sample_seq)
print("features")
print(x)
print("output")
print(y)
print("--------------")
later_use_x=x
later_use_y=y

----------------
raw
[444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444.6694018, 444

In [10]:
features=1
x=x.reshape((x.shape[0] , x.shape[1] , features))
print("after reshaping")
print(x.shape)
print("------------")
print(x)

after reshaping
(58729, 1000, 1)
------------
[[[444.6694018]
  [444.6694018]
  [444.6694018]
  ...
  [444.6694018]
  [444.6694018]
  [444.6694018]]

 [[444.6694018]
  [444.6694018]
  [444.6694018]
  ...
  [444.6694018]
  [444.6694018]
  [444.6694018]]

 [[444.6694018]
  [444.6694018]
  [444.6694018]
  ...
  [444.6694018]
  [444.6694018]
  [444.6694018]]

 ...

 [[303.       ]
  [325.25     ]
  [275.       ]
  ...
  [515.       ]
  [515.       ]
  [450.       ]]

 [[325.25     ]
  [275.       ]
  [240.75     ]
  ...
  [515.       ]
  [450.       ]
  [437.       ]]

 [[275.       ]
  [240.75     ]
  [272.5      ]
  ...
  [450.       ]
  [437.       ]
  [397.25     ]]]


In [11]:
model = Sequential()
model.add(Conv1D(filters =64 , kernel_size=2 , activation ='relu', input_shape=(steps,features)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(1))
model.compile(optimizer= 'adam', loss='mse')

In [ ]:
model.fit(x,y,epochs=100,verbose=0)

In [ ]:
x_input=later_use_x
x_input = x_input.reshape((x.shape[0] , x.shape[1] , features))
y_pred= model.predict(x_input, verbose=0)
print(len(y_pred))
print(y_pred)


In [ ]:
print(len(later_use_y))
print(later_use_y[200:210])
plt.plot(later_use_y)
plt.plot(y_pred, color='red')

In [ ]:
from sklearn.metrics import mean_absolute_error

mean_absolute_error(later_use_y,y_pred)